# Generated by Django 5.1.10 on 2025-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_timestamp",
                    models.DateTimeField(
                        help_text="Timestamp when the log entry was recorded"
                    ),
                ),
                (
                    "machine_id",
                    models.CharField(
                        help_text="Unique identifier for the machine", max_length=50
                    ),
                ),
                (
                    "operator_id",
                    models.CharField(
                        help_text="Identifier for the machine operator", max_length=50
                    ),
                ),
                (
                    "engine_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total engine hours recorded",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fuel_used_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fuel consumed in liters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "load_cycles",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of load cycles performed",
                        null=True,
                    ),
                ),
                (
                    "idling_time_min",
                    models.IntegerField(
                        blank=True, help_text="Time spent idling in minutes", null=True
                    ),
                ),
                (
                    "seatbelt_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FASTENED", "Fastened"),
                            ("UNFASTENED", "Unfastened"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        help_text="Status of operator seatbelt",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "safety_alert_triggered",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether a safety alert was triggered during operation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Machine Log",
                "verbose_name_plural": "Machine Logs",
                "db_table": "machine_logs",
                "ordering": ["-log_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["machine_id", "log_timestamp"],
                        name="machine_log_machine_5d96c3_idx",
                    ),
                    models.Index(
                        fields=["operator_id"], name="machine_log_operato_b717c8_idx"
                    ),
                    models.Index(
                        fields=["log_timestamp"], name="machine_log_log_tim_891079_idx"
                    ),
                ],
            },
        ),
    ]
